name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'Homeworks/06 Настройка CI/**'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/tonylyad/promocode-factory-api

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Логинимся в GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build test stage
        uses: docker/build-push-action@v6
        with:
          context: ./Homeworks/06 Настройка CI/src
          file: ./Homeworks/06 Настройка CI/src/Dockerfile
          target: test
          push: false

      - name: Build и push image
        uses: docker/build-push-action@v6
        with:
          context: ./Homeworks/06 Настройка CI/src
          file: ./Homeworks/06 Настройка CI/src/Dockerfile
          target: final
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}